name = "Antharangam"
license = "AGPL-3.0-or-later"
licenselink = "https://github.com/opendatakerala/mapkerala/blob/master/LICENSE"
description = ""
homepage = "http://opendatakerala.org/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Akshay S Dinesh"
  homepage = "https://asd.learnlearn.in"
