baseURL = "https://map.opendatakerala.org/"
languageCode = "en-us"
title = "Map Kerala"

[params]
  description = 'A Gateway to Your Geospatial Map Data of Kerala'
  title = 'Map Kerala'

# prevent Kannur becoming Kannurs
pluralizelisttitles = "false"

[outputs]
  page = ["HTML", "JSON"]