baseURL = "https://map.opendatakerala.org/"
languageCode = "en-us"
title = "Map Kerala"

# prevent Kannur becoming Kannurs
pluralizeListTitles = false

[params]
  description = 'A Gateway to Your Geospatial Map Data of Kerala'
  title = 'Map Kerala'

[outputs]
  page = ["HTML", "JSON"]

[markup.goldmark.renderer]
  unsafe = true # to have html in md